### ISSUE TITLE
No content shown

### ISSUE THREAD

**Issue by michaelkisiel** [1000ch/whale#4]
On Ubuntu 16.04.01 starting the app ends in opening the panel only seeing background colors of site, but no buttons and no boards are shown

**Comment by klauscfhq** [comment]
Hi!
Trello uses a third party service called **CDN** or **Content Delivery Network**, in order to make their app faster and provide their users with a better experience. CDN is mostly used for delivering files to the user, that are closer to user's physical location. So, since they do not control these resources immediately, _because these resources don't originate from Trello.com_, they sometimes can be blocked by a number of factors. Most of the times, that factor is an interfering **firewall**, blocking the app. 

Other reason might be;
- the DNS not resolving
- issues regarding the app/browser. 

In essence Whale is an Electron wrap of the web version of Trello.com, something like a a browser that is specifically engineered to load the Trello website. 

There is a number of ways you can try resolving the issue:
- Try pressing **Ctrl + F5** or **Ctrl + Shift + R** and then **restart** the app
- **Whitelist** the app from your firewall, if you have one deployed on your Linux machine
- Try **clearing** your **DNS cache** on your local machine. [Here is a cheat sheet](https://www.liquidweb.com/kb/flush-dns-cache/) on how to do that, for all three major OS-s.

Hope it helps! ✌️ 
 
In case that none of the above is of any use, it could be a Electron-related issue and probably only a future update could resolve.

**Comment by michaelkisiel** [comment]
Nothing worked for me :disappointed: i cant say if it is a electron related problem, because it worked flawlessly for me. It changed when generating a whale.desktop file as a startup-file...

**Comment by designsbytraina** [comment]
Experiencing a similar issue on macOS with button disabled and warnings abound. Trying what @klauscfhq suggested. 👍

**Comment by vitorgalvao** [comment]
This looks related/the same as https://github.com/1000ch/whale/issues/3.

The latest version (released yesterday) should fix it.

**Comment by klauscfhq** [comment]
On my end, the latest [🐳 v0.7.0](https://github.com/1000ch/whale/releases/tag/v0.7.0) release works like a charm **@ Windows 10 Pro**  ✌️

**Comment by 1000ch** [comment]
This problem seems to be fixed from `v0.7.0`.
